### PR TITLE
React-Resume-workshop

### PR DESCRIPTION
**Pull request by sandykr01**

### CODE REVIEW

**Comment by sandykr01** [comment]
hello please do consider my PR as I am new to git so, I don't know how to do it.

**Comment by Anmolreshi** [comment]
Kindly provide Live Link to website to check @sk9873422561

**Comment by sandykr01** [comment]
Do I need to deploy it, or I can share the link of sandbox like praveen and there you can verify it. Will it be ok?

**Comment by Anmolreshi** [comment]
Send Link of sandbox if you have hosted it there

**Comment by sandykr01** [comment]
https://codesandbox.io/s/flamboyant-pond-fq02p?file=/src/config.json:292-667

**Comment by sandykr01** [comment]
Just go to the config file and update the required info and you will get to see all the changes.

**Comment by Anmolreshi** [comment]
Good work

**Pull request closed without merging**
