### PR TITLE
Portfolio website using React

### PR DESCRIPTION
**Pull request by geekymeeky**
- Created a portfolio website using ReactJS
- Screenshot:
image
- You can view this on: https://geekymeeky.github.io/Web-dev-Workshop-by-praveen-/

### CODE REVIEW

**Comment by Anmolreshi** [comment]
Good work

**Comment by Anmolreshi** [comment]
Congratulations You Have made Best Project and added many enhancements . Kindly write your email for reward for the Task .

**Comment by geekymeeky** [comment]
> Congratulations You Have made Best Project and added many enhancements . Kindly write your email for reward for the Task .
Yaay!.  :partying_face: 
Email: gupta.srijan94@gmail.com

**Comment by geekymeeky** [comment]
@Anmolreshi I haven't received any email yet.

**Comment by Anmolreshi** [comment]
Soon You would be getting mail . Don't worry Team is on it

**Pull request merged**
